baseURL = "https://karala.org"
enableRobotsTXT = "true"
languageCode = "tr"
relativeURLs = true
theme = ["hugo-search-fuse-js", "karala"]
title = "Anarşist Dergi | KARALA"
[Social]
twitter = "karala"
[[menu.main]]
identifier = "categories"
name = "Dergi"
pygmentsCodeFences = true
pygmentsUseClasses = true
url = "/categories/"
weight = 6
[[menu.main]]
identifier = "kara-kose"
name = "Kara Köşe"
url = "/kara-kose/"
weight = 5
[[menu.main]]
identifier = "eylemlerimiz"
name = "Eylem"
url = "/eylem/"
weight = 4
[[menu.main]]
identifier = "orgutlen"
name = "Örgütlen"
url = "/orgutlen/"
weight = 2
[[menu.main]]
identifier = "admin"
name = "Giriş Yap"
url = "https://app.forestry.io/sites/snp4o-4iwuufcg/#/sections/posts/content/posts"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Yazılar"
url = "/posts/"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
baslik = "Yazılar"
baslikkategori = "Kategori"
facebook = "karaladergi"
instagram = "karaladergi"
twitter = "karaladergi"
yazar = "karala"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
