baseURL = "https://karala.org"
languageCode = "tr"
title = "Anarşist Dergi | KARALA"
enableRobotsTXT = "true" 

theme = ["hugo-search-fuse-js", "karala"]
#theme = "karala"
relativeURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]


[menu]

 [[menu.main]]
    identifier = "admin"
    name = "Giriş Yap"
    url = "https://app.forestry.io/sites/djp4eawewz-otq/#/sections/posts/content/posts"
    weight = 100

  [[menu.main]]
    identifier = "orgutlen"
    name = "Örgütlen"
    url = "/orgutlen/"
    weight = 100

#  [[menu.main]]
#    identifier = "tags"
#    name = "Etiketler"
#    url = "/tags/"
#    weight = 110

  [[menu.main]]
    identifier = "posts"
    name = "Yazılar"
    url = "/posts/"
    weight = 120

  [[menu.main]]
    identifier = "eylemlerimiz"
    name = "Eylemlerimiz"
    url = "/eylemlerimiz/"
    weight = 120

  [[menu.main]]
    identifier = "kara-kose"
    name = "Kara Köşe"
    url = "/kara-kose/"
    weight = 130



 [[menu.main]]
    identifier = "categories"
    name = "Dergi"
    url = "/categories/"
    weight = 100





#Adding code highlight  themes/karala/static/css/syntax.css

pygmentsCodeFences = true
pygmentsUseClasses = true



#add variable

[params]

baslik = "Yazılar"
baslikkategori = "Kategori"
instagram = "karaladergi"
twitter = "karaladergi"
facebook = "karaladergi"
yazar = "karala"


## social card


[Social]
  twitter = "karala"


#add sitemap.xml

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5




## STORE ##

#{{ range first 5 (where .Pages "Type" "posts") }} # themes/karala/layouts/index.html at 205
